import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
//Added the clerk provider here in the main layout file 
import { ClerkProvider } from "@clerk/nextjs";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sync-Connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    //here wrapped the whole application with the clerk provider
    <ClerkProvider>
      <html lang="en">
      <body className={font.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
