import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
//Added the clerk provider here in the main layout file 
import { ClerkProvider } from "@clerk/nextjs";

//imported the dark theme thingy from shadcn and wrapping the children in it
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";
import { ModelProvider } from "@/components/providers/model-provider";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sync-Connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    //here wrapped the whole application with the clerk provider
    <ClerkProvider>
      {/* added suppressHydrationWarning in html */}
      <html lang="en" suppressHydrationWarning>
      <body className={cn (
        font.className,
        "bg-white dark:bg-[#313338]"
        )}>
        <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        enableSystem={false}
        storageKey="syncconnect-theme"
        >
        <ModelProvider/>
        {children}
        </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
